export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_SURVEYS = "fetch_surveys";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const LOG_OUT = "LOG_OUT";
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SUBMIT_SURVEY = "SUBMIT_SURVEY";
export const DELETE_SURVEY = "DELETE_SURVEY";
export const RESPOND_SURVEY = "RESPOND_SURVEY";
export const UPDATE_CREDIT = "UPDATE_CREDIT";
export const ADMIN_SIGNUP_SUCCESSFULL = "ADMIN_SIGNUP_SUCCESSFULL";
export const ALL_SURVEYS_FETCHED = "ALL_SURVEYS_FETCHED";
export const ALL_USER_FETCHED = "ALL_USER_FETCHED";
export const SET_SHOW_SURVEYS = "SET_SHOW_SURVEYS";
export const DECREASE_CREDIT = "DECREASE_CREDIT";
